Fix python version in e2e image (#201)
* Unpin python version

In the mean time python version in 'world' changed and pinned version causes image build to fail

```
ERROR: unable to select packages:
  python3-3.11.6-r0:
    breaks: world[python3=3.11.5-r0]
    satisfies: python3-3.11.6-r0[python3~3.11]
```

* Pin higher version instead

As this is one time build we can leave it at that anyway to satisfy linter.